version: '3.4'

services:
  microservice.produtos.webapi:
    image: ${DOCKER_REGISTRY-}microserviceprodutoswebapi
    build:
      context: .
      dockerfile: Microservice.Produtos.WebApi/Dockerfile
    depends_on:
        - mssql
    links:
        - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Hiper@987!@!@!@"
        ACCEPT_EULA: "Y"

