version: '3.4'

services:
  microservice.produtos.webapi:
    image: ${DOCKER_REGISTRY-}microserviceprodutoswebapi
    container_name: microservice-produtos-webapi
    build:
      context: .
      dockerfile: Microservice.Produtos.WebApi/Dockerfile
    depends_on:
        - mssql
    links:
        - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql-server
    ports:
        - "1433:1433"
    volumes:
        - .mssql\data:/var/opt/mssql/data
        - .mssql\log:/var/opts/mssql/log
        - .mssql\secrects:/var/opt/mssql/secrects

    environment:
        SA_PASSWORD: "Hiper@987!@!@!@"
        ACCEPT_EULA: "Y"